CREATE TABLE Student ( id INTEGER PRIMARY KEY AUTOINCREMENT, 	
	Name VARCHAR(255), lastname VARCHAR(255) );
CREATE TABLE Marks ( id INTEGER PRIMARY KEY AUTOINCREMENT, 	
	Russian INTEGER,  Math INTEGER, Physics INTEGER,	student_id INTEGER,  	
	FOREIGN KEY(student_id) REFERENCES student(id));

